#!/usr/bin/env bash
# This script displayes information about subdomains.

sub_domains=( "www" "lb-01" "web-01" "web-02" )
domain="$1"
sub="$2"

dig_cmd () {
        sub=$2
        record="$(dig "$sub.$domain" | grep -A1 "ANSWER SECTION:" | awk 'NR==2')"
        r_type="$(echo "$record" | awk '{print $4}')"
        ip="$(echo "$record" | awk '{print $5}')"
        echo "The subdomain $sub is a $r_type record and points to $ip"
}
if [ $# -eq 1 ]
then
        for subs in "${sub_domains[@]}"
        do
                dig_cmd "$domain" "$subs"
        done
elif [ $# -eq 2 ]
then
        dig_cmd "$domain" "$sub"
fi
