#!/usr/bin/env bash
# This Bash script that transfers a file from our client to a server:
if [ "$#" -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file="$1"
	ip="$2"
	user="$3"
	private_key="$4"
	scp -o StrictHostKeyChaking=no -i "$private_key" "$file" "$user@$ip":~/;
fi
