#!/usr/bin/env bash
apt -y update
apt -y install nginx
#sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
mkdir -p /var/www/html
chmod -R 755 /var/www
ufw allow 'Ngnix HTTP'
echo "Hello World!" > /var/www/html/index.html
service ngnix start
