#!/usr/bin/env bash
# This command Installs nginx web server
# returns a page with string hello world
sudo apt-get -y update
sudo apt-get -y install nginx
#sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
sudo mkdir -p /var/www/html
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo service ngnix start
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
# Setting up /redirect_me to a youtube video
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
# Restarting nginx
sudo service nginx restart
