#!/usr/bin/env bash
# This command Installs nginx web server
# returns a page with string hello world

command -v "$1" &> /dev/null
if [ $? -ne 0 ]; then
	apt-get -y update
	apt-get -y install nginx
else
	echo "already installed \n"
fi
#sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default

ufw allow 'Nginx HTTP'

if [ -d "/var/www" ]; then
	sudo chown -R $USER:$USER /var/www/html
	sudo chmod -R 755 /var/www
else
	mkdir -p /var/www/html
	chown -R $USER:$USER /var/www/html
	chmod -R 755 /var/www
fi

echo "Hello World!" > /var/www/html/index.html

# backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html
	server_name_;
	add_header X-Served-By \$hostname;
	location / {
	try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://th3-gr00t.tk/ permanent;
	}
	error_page 404 /error_404.html;
	location = /error_404.html {
	internal;
	}
}"

#shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
