#!/usr/bin/env bash
# Create mysql dump file and compress dump file for buckup

PASS="$1"
DATE=$(date +%d-%m-%y)
mysqldump -uroot -p"$PASS" --opt --all-databases > backup.sql
tar -zcvf "$DATE".tar.gz backup.sql
