#!/usr/bin/env/bash
# This bash script tries to configure "Failed to connect to 0 port 80: fix.
sudo ufw allow 80
sudo sed -i "22s/listen .*/listen 80" /etc/nginx/sites-enabled/default
sudo service ngnix restart
