#!/usr/bin/env bash
#displays numbers from 1 to 100.

#Requirements:

#Displays FizzBuzz when the number is a multiple of 3 and 5
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5

for ((c = 1; c <= 100; c++))
do
	((a = c % 3))
	((b = c % 5))
	if [ $a -eq 0 ] && [ $b -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $a -eq 0 ]
	then
		echo "Fizz"
	elif [ $b -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$c"
	fi
done
