#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
input="/etc/passwd"
while IFS= read -r line
do
	echo "The user $(echo "$line" | cut -d ':' -f1) is part of the $(echo "$line" | cut -d ':' -f4) gang, lives in $(echo "$line" | cut -d ':' -f6) and rides $(echo "$line" | cut -d ':' -f7). $(echo "$line" | cut -d ':' -f3)'s place is protected by the passcode $(echo "$line" | cut -d ':' -f2), more info about the user here: $(echo "$line" | cut -d ':' -f5)"
done < "$input"
