#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

#Requirement:

#Format: IP HTTP_CODE , in a list format
file="$(pwd)/apache-access.log"
awk '{print $1, $9}' "$file" | sort | uniq -c | sort -nr | head
