#!/usr/bin/env bash
#displays Best School 10 times
i=0
while [ $i -lt 10 ]
do
        if [[ "$i" -eq "3" ]]
        then
                echo "bad luck"
		((i++))
		continue
	fi
	if [[ "$i" -eq "7" ]]
	then
		echo "good luck"
		((i++))
		continue
        fi
        ((i++))
        echo "Best School"
done

